/*
ِAbout frame
 */
package forms;

import ayat.Tools;
import java.awt.ComponentOrientation;
import java.awt.Desktop;
import java.net.URI;


/**
 *
 * @author hishamls
 */
public class frm_ayat_ar_about extends javax.swing.JFrame {

    /**
     * Creates new form frm_ayat_about_ar
     */
    public frm_ayat_ar_about() {
        initComponents();
        setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jPanel1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txt_program_Name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txt_Programer.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txt_EMail.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txt_phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lbl_EMail.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lbl_phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lbl_program.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lbl_programer.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        btn_close.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        btn_coby.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lbl_cobied.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        lbl_cobied.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_program = new javax.swing.JLabel();
        txt_program_Name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Programer = new javax.swing.JTextField();
        lbl_programer = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_phone = new javax.swing.JTextField();
        lbl_EMail = new javax.swing.JLabel();
        txt_EMail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btn_close = new java.awt.Button();
        btn_coby = new java.awt.Button();
        lbl_cobied = new javax.swing.JLabel();
        lbl_website = new javax.swing.JLabel();
        txt_web = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btn_browse = new java.awt.Button();
        lbl_program1 = new javax.swing.JLabel();
        txt_program_Name1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "عن البرنامج", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Kufi Arabic", 1, 18), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        lbl_program.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_program.setForeground(new java.awt.Color(0, 51, 51));
        lbl_program.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_program.setText("اسم البرنامج");

        txt_program_Name.setEditable(false);
        txt_program_Name.setBackground(new java.awt.Color(255, 0, 153));
        txt_program_Name.setFont(new java.awt.Font("Noto Kufi Arabic", 0, 14)); // NOI18N
        txt_program_Name.setForeground(new java.awt.Color(0, 51, 51));
        txt_program_Name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_program_Name.setText("آيات تحفيظ القرآن الكريم");
        txt_program_Name.setToolTipText("");
        txt_program_Name.setBorder(null);

        txt_Programer.setEditable(false);
        txt_Programer.setBackground(new java.awt.Color(255, 0, 153));
        txt_Programer.setFont(new java.awt.Font("Noto Kufi Arabic", 0, 14)); // NOI18N
        txt_Programer.setForeground(new java.awt.Color(0, 51, 51));
        txt_Programer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Programer.setText("هشام صقر");
        txt_Programer.setBorder(null);

        lbl_programer.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_programer.setForeground(new java.awt.Color(0, 51, 51));
        lbl_programer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_programer.setText("اسم المبرمج");

        lbl_phone.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(0, 51, 51));
        lbl_phone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_phone.setText("محمول");

        txt_phone.setEditable(false);
        txt_phone.setBackground(new java.awt.Color(255, 0, 153));
        txt_phone.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        txt_phone.setForeground(new java.awt.Color(0, 51, 51));
        txt_phone.setText("00201090209759");
        txt_phone.setBorder(null);

        lbl_EMail.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_EMail.setForeground(new java.awt.Color(0, 51, 51));
        lbl_EMail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_EMail.setText("البريد الألكتروني");

        txt_EMail.setEditable(false);
        txt_EMail.setBackground(new java.awt.Color(255, 0, 153));
        txt_EMail.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        txt_EMail.setForeground(new java.awt.Color(0, 51, 51));
        txt_EMail.setText("modernhisham@gmail.com");
        txt_EMail.setBorder(null);

        btn_close.setActionCommand("مستخدم جديد");
        btn_close.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        btn_close.setForeground(new java.awt.Color(0, 51, 51));
        btn_close.setLabel("انهاء");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_coby.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        btn_coby.setForeground(new java.awt.Color(0, 51, 51));
        btn_coby.setLabel("انسخ");
        btn_coby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cobyActionPerformed(evt);
            }
        });

        lbl_cobied.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_cobied.setForeground(new java.awt.Color(204, 0, 51));
        lbl_cobied.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cobied.setText("تم النسخ");

        lbl_website.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_website.setForeground(new java.awt.Color(0, 51, 51));
        lbl_website.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_website.setText("الموقع الألكتروني");

        txt_web.setEditable(false);
        txt_web.setBackground(new java.awt.Color(255, 0, 153));
        txt_web.setFont(new java.awt.Font("Chilanka", 0, 12)); // NOI18N
        txt_web.setForeground(new java.awt.Color(0, 51, 51));
        txt_web.setText("http://www.google.com");
        txt_web.setBorder(null);

        btn_browse.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        btn_browse.setForeground(new java.awt.Color(0, 51, 51));
        btn_browse.setLabel("تصفح");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        lbl_program1.setFont(new java.awt.Font("Noto Sans Arabic UI", 1, 14)); // NOI18N
        lbl_program1.setForeground(new java.awt.Color(0, 51, 51));
        lbl_program1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_program1.setText("الأصدار");

        txt_program_Name1.setEditable(false);
        txt_program_Name1.setBackground(new java.awt.Color(255, 0, 153));
        txt_program_Name1.setFont(new java.awt.Font("Noto Kufi Arabic", 0, 14)); // NOI18N
        txt_program_Name1.setForeground(new java.awt.Color(0, 51, 51));
        txt_program_Name1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_program_Name1.setText("1");
        txt_program_Name1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_program_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lbl_program, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(754, 754, 754)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(582, 582, 582))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_coby, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Programer, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lbl_programer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(229, 229, 229)
                                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_web, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_website, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(352, 352, 352)
                                    .addComponent(lbl_cobied, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_program_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lbl_program1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_program_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_program, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_program_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_program1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Programer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_programer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_coby, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_web, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_website, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cobied, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
        Tools.openForm(new frm_ayat_ar_log());
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_cobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cobyActionPerformed
        txt_EMail.copy(); //not work
        lbl_cobied.setVisible(true);

        
    }//GEN-LAST:event_btn_cobyActionPerformed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        try {
//             Desktop desk= Desktop.getDesktop();
//URI uri= new URI("http://www.google.com");//"http://" is very important to under-
//stand that is not a string.
//        Desktop.getDesktop().browse(uri); // URI not URL
        Desktop.getDesktop().browse(new URI(txt_web.getText()));// shortcut for 
//        above
        } catch (Exception e) {
            e.getMessage();
        }
//        try {
//   
//   URI uri= new URI("http://www.instanceofjava.com");
//   
//   java.awt.Desktop.getDesktop().browse(uri);
////    System.out.println("Web page opened in browser");
// 
//  } catch (Exception e) {
//   
//   e.printStackTrace();
//  }
 
        
    }//GEN-LAST:event_btn_browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ayat_ar_about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ayat_ar_about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ayat_ar_about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ayat_ar_about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ayat_ar_about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_browse;
    private java.awt.Button btn_close;
    private java.awt.Button btn_coby;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_EMail;
    private javax.swing.JLabel lbl_cobied;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_program;
    private javax.swing.JLabel lbl_program1;
    private javax.swing.JLabel lbl_programer;
    private javax.swing.JLabel lbl_website;
    private javax.swing.JTextField txt_EMail;
    private javax.swing.JTextField txt_Programer;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_program_Name;
    private javax.swing.JTextField txt_program_Name1;
    private javax.swing.JTextField txt_web;
    // End of variables declaration//GEN-END:variables
}
